global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'sarah-alerts'
  
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
    continue: true
  
  - match:
      severity: warning
    receiver: 'warning-alerts'

receivers:
- name: 'sarah-alerts'
  webhook_configs:
  - url: 'http://sarah-api:8000/webhooks/alerts'
    send_resolved: true

- name: 'critical-alerts'
  webhook_configs:
  - url: 'http://sarah-api:8000/webhooks/alerts/critical'
    send_resolved: true
  # Add email/SMS/Slack configurations here for critical alerts

- name: 'warning-alerts'
  webhook_configs:
  - url: 'http://sarah-api:8000/webhooks/alerts/warning'
    send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']