# SwiftLint configuration for Sarah AI

# Opt-in rules
opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - fatal_error_message
  - file_name
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Disabled rules
disabled_rules:
  - todo
  - trailing_comma
  - line_length

# Rule configurations
identifier_name:
  min_length: 2
  max_length: 50
  allowed_symbols: ["_"]
  validates_start_with_lowercase: false

type_name:
  min_length: 3
  max_length: 50

function_body_length:
  warning: 60
  error: 100

file_length:
  warning: 600
  error: 1000

type_body_length:
  warning: 300
  error: 500

large_tuple:
  warning: 3
  error: 4

function_parameter_count:
  warning: 6
  error: 8

cyclomatic_complexity:
  warning: 15
  error: 20

nesting:
  type_level:
    warning: 2
  function_level:
    warning: 3

# Paths
included:
  - Experience
  - Core
  - Agents
  - Bridges
  - Sanctuary
  - Tests

excluded:
  - Carthage
  - Pods
  - .build
  - DerivedData
  - fastlane

# Reporter
reporter: "xcode"