# Prometheus configuration for Sarah AI monitoring

global:
  scrape_interval: 15s # Default scrape interval
  evaluation_interval: 15s # How frequently to evaluate rules
  external_labels:
    monitor: 'sarah-ai'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093'

# Load rules once and periodically evaluate them
rule_files:
  - '/etc/prometheus/rules/*.yml'

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    
  # FastAPI application metrics
  - job_name: 'sarah-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['sarah-api:8000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'sarah-api'
  
  # PostgreSQL exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'postgres'
  
  # Redis exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'redis'
  
  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'docker-host'
  
  # Cadvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'containers'
  
  # Agent health endpoints
  - job_name: 'sarah-agents'
    metrics_path: '/agents/health'
    static_configs:
      - targets: ['sarah-api:8000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'agents'